[package]
name = "grow"
version = "0.1.0"
edition = "2021"

# TODO: See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "^0.25"
pulldown-cmark = { version = "^0.9.2", default-features = false}
notify = "^5.1.0"